name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: TestProjectOlimpia/mi-firma@main
        env:
          API_TOKEN_GITHUB: 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
        with:
          source-directory: 'output'
          destination-github-username: 'TestProjectOlimpia'
          destination-repository-name: 'mi-firma'
          user-email: brayan.rodriguez@olimpiait.com
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: main
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
